package name.starnberger.guenther.android.smsticket;

public final class Station {
	public static final String[] STATIONS = new String[] { "Abfaltersbach",
			"Absberg", "Absdorf-Hippersdorf", "Achau", "Achenlohe",
			"Achleitnersiedlung", "Admont", "Aggsbach Markt",
			"Aich im Jauntal", "Aich-Assach", "Aigen-Schlägl", "Aisthofen",
			"Allentsteig", "Allerheiligen-Mürzhofen", "Allerheiligenhöfe",
			"Altach", "Altenhof", "Altenmarkt im Pongau", "Altenstadt",
			"Altmünster am Traunsee", "Altpinkafeld", "Amstetten",
			"Amt Mitterbach", "Andorf", "Angern", "Angertal", "Annaberg",
			"Annenheim", "Ansfelden", "Antiesenhofen", "Arbing", "Ardning",
			"Arnoldstein", "Aschach a. d. Donau", "Aschbach", "Aspang",
			"Asten-Fisching", "Attnang-Puchheim", "Atzenbrugg", "Auersthal",
			"Aurachkirchen", "Aurolzmünster Haltestelle", "Ausschlag-Zöbern",
			"Authal", "Bad Aussee", "Bad Blumau", "Bad Deutsch Altenburg",
			"Bad Erlach", "Bad Fischau", "Bad Fischau-Brunn", "Bad Gastein",
			"Bad Goisern", "Bad Hofgastein", "Bad Hofgastein Haltestelle",
			"Bad Ischl", "Bad Mitterndorf", "Bad Mitterndorf-Heilbrunn",
			"Bad Pirawarth", "Bad Radkersburg", "Bad Ried", "Bad Sauerbrunn",
			"Bad Schallerbach-Wallern", "Bad St. Leonhard", "Bad Vigaun",
			"Bad Vöslau", "Bad Waltersdorf", "Baden", "Baumgartenberg",
			"Berg im Drautal", "Bergern", "Berndorf Fabrik", "Berndorf Stadt",
			"Bernhardsthal", "Bernschlag", "Bierbaum", "Bisamberg",
			"Bischofshofen", "Bischofstetten", "Blamau", "Bleiburg",
			"Bleiburg Stadt", "Blindenmarkt", "Bludenz", "Bockfließ", "Boding",
			"Braunau am Inn", "Bregenz", "Bregenz Hafen", "Breitenaich",
			"Breitenbrunn", "Breiteneich bei Horn", "Breitenschützing",
			"Breitensee NÖ", "Breitenstein", "Breitenwaida", "Breitwiesen",
			"Brennero/Brenner", "Brixen im Thale", "Brixlegg",
			"Bruck a. d. Leitha", "Bruck a. d. Mur", "Bruck-Fusch",
			"Brunn a. d. Pitten", "Brunn a. d. Schneebergbahn",
			"Brunn-Maria Enzersdorf", "Buchberg", "Buchs SG", "Böckstein",
			"Böheimkirchen", "Böhlerwerk a.d. Ybbs",
			"Campus Krems - Kunstmeile Krems", "Dechantskirchen",
			"Dellach im Drautal", "Dellach im Gailtal", "Deutsch Wagram",
			"Deutschkreutz", "Diensthubersiedlung", "Dietrichshofen",
			"Donnerskirchen", "Dorf a. d. Enns", "Dorfgastein", "Dornach",
			"Dornbirn", "Dornbirn-Schoren", "Dreistetten", "Drösing",
			"Dölsach", "Dürnbach", "Dürnberg", "Dürnkrut",
			"Dürnstein-Oberloiben", "Dürrwien", "Eben im Pongau", "Ebenfurth",
			"Ebensee", "Ebensee Landungsplatz", "Eberschwang", "Ebreichsdorf",
			"Ederbauer", "Ederlehen", "Edlitz-Grimmenstein", "Eferding",
			"Eggenburg", "Ehrenhausen", "Eichberg", "Eichgraben-Altlengbach",
			"Eis-Ruden", "Eisenstadt", "Eisenstadt Schule", "Elsbethen",
			"Emmersdorf", "Emmersdorf a. d. Donau", "Enns", "Ennsdorf",
			"Enzersdorf bei Staatz", "Enzesfeld-Lindabrunn", "Eppenstein",
			"Erlauf", "Erlaufklause", "Ernsthofen", "Eschenau",
			"Etsdorf-Strass", "Eugendorf", "Faak am See", "Fahrafeld",
			"Fehring", "Feistritz im Rosental", "Feistritz im Rosental West",
			"Feldbach", "Feldkirch", "Feldkirch-Amberg",
			"Feldkirchen in Kärnten", "Feldkirchen-Seiersberg", "Felixdorf",
			"Fels", "Fentsch-St. Lorenzen", "Ferndorf", "Feuerwerksanstalt",
			"Fieberbrunn", "Finkenstein", "Finklham", "Fischamend",
			"Flaurling", "Flughafen Graz-Feldkirchen", "Flughafen Wien",
			"Forst-Hilti", "Frankenfels", "Frankenmarkt",
			"Frantschach-St. Gertraud", "Frastanz", "Frauenberg a. d. Enns",
			"Freiland", "Freistadt", "Friedberg", "Friedburg", "Friesach",
			"Fritzens-Wattens", "Frohnleiten", "Frättingsdorf", "Furth",
			"Furth-Göttweig", "Furth-Palt", "Furthof", "Föderlach", "Fürnitz",
			"Fürstenfeld", "Gaflenz", "Gaisbach-Wartberg", "Gaishorn",
			"Gaisruck", "Gaissulz", "Ganz", "Gars-Thunau", "Garsten",
			"Gattendorf", "Gedersdorf", "Geinberg", "Gemeinlebarn",
			"Gerasdorf", "Gerling OÖ", "Gerling im Pinzgau", "Gerotten",
			"Getzersdorf", "Gießenbach", "Gisingen", "Glandorf", "Glanegg",
			"Glaubendorf-Wetzdorf", "Gleisdorf", "Gleißenfeld", "Glinzendorf",
			"Gloggnitz", "Gmunden", "Gmünd NÖ", "Gniebing", "Gobelsburg",
			"Goisern Jodschwefelbad", "Golling-Abtenau", "Gopperding",
			"Gosdorf", "Grafendorf", "Grafenstein", "Gramatneusiedl",
			"Granitztal", "Gratwein-Gratkorn", "Graz Don Bosco",
			"Graz Hauptbahnhof", "Graz Ostbahnhof", "Greifenburg-Weissensee",
			"Greifenstein-Altenberg", "Grein Stadt", "Grein-Bad Kreuzen",
			"Greinsfurth", "Gries", "Gries im Pinzgau",
			"Grieskirchen-Gallspach", "Grieswirt", "Grimsing",
			"Groß Engersdorf", "Groß Globnitz", "Groß Haslau",
			"Groß Schweinbarth", "Groß Sierning", "Groß Weikersdorf",
			"Großendorf", "Großhollenstein", "Großraming",
			"Großraming Kraftwerk", "Großreifling",
			"Großwiesendorf-Tiefenthal", "Gröbming", "Grünau im Almtal",
			"Grünbach Kohlenwerk", "Grünbach Schule", "Grünbach am Schneeberg",
			"Gstadt", "Gstatterboden im Nationalpark", "Gummern",
			"Gumpoldskirchen", "Gundersheim", "Gunskirchen", "Guntersdorf",
			"Guntramsdorf Südbahn", "Guntramsdorf-Kaiserau", "Gurhof",
			"Gurten", "Gutenstein", "Gänserndorf", "Göblasbruck", "Gödersdorf",
			"Göllersdorf", "Göpfritz", "Görtschach-Förolach", "Gösing",
			"Göstling a. d. Ybbs", "Götzendorf", "Götzis", "Haag",
			"Hadersdorf am Kamp", "Hagenau im Innkreis", "Haiding", "Haiming",
			"Hainburg Ungartor", "Hainburg a. d. Donau Frachtenbf",
			"Hainburg a. d. Donau Personenbf", "Hainfeld", "Halbenrain",
			"Hall in Tirol", "Hallein", "Hallein Burgfried", "Hallstatt",
			"Hallwang-Elixhausen", "Hard-Fussach", "Hart im Innkreis",
			"Hart-Wörth", "Hartberg", "Haselstauden", "Haslach", "Haslau",
			"Hatlerdorf", "Hatting", "Hatzendorf", "Haus", "Hausleiten",
			"Hausruck", "Hautzendorf", "Heinrichsberg", "Helmahof",
			"Hennersdorf", "Hermagor", "Herzogenburg", "Herzogenburg Stadt",
			"Herzogenburg-Wielandsthal", "Herzograd",
			"Hetzmannsdorf-Wullersdorf", "Hieflau", "Hilm-Kematen", "Himberg",
			"Hinterstoder", "Hirschbach", "Hirschenau-Nöchling", "Hirtenberg",
			"Hochfilzen", "Hochzirl", "Hofstatt", "Hofstetten-Grünau",
			"Hohenau", "Hohenberg", "Hohenbrugg a. d. Raab", "Hohenems",
			"Hohenlehen", "Hohenruppersdorf", "Hollabrunn", "Holzleithen",
			"Hopfgarten", "Hopfgarten Berglift", "Horn", "Hubertendorf",
			"Höbersdorf", "Höflein a. d. Donau", "Hönigsberg", "Hörersdorf",
			"Hörmanns", "Hörsching", "Hötzelsdorf-Geras", "Hüttau", "Iglmühle",
			"Imst-Pitztal", "Imsterberg", "In der Bruck", "Innerfahrafeld",
			"Innsbruck Hauptbahnhof", "Innsbruck Hötting",
			"Innsbruck Westbahnhof", "Inzing", "Irnfritz", "Irschen",
			"Jedenspeigen", "Jenbach", "Jennersdorf",
			"Johnsbach im Nationalpark", "Jois", "Judenau-Sieghartskirchen",
			"Judenburg", "Judendorf-Straßengel", "Kahlenbergerdorf",
			"Kaindorf a. d. Sulm", "Kainisch", "Kalköfen-Daxberg", "Kalsdorf",
			"Kalwang", "Kamegg", "Kammer-Schörfling", "Kammerhof", "Kammern",
			"Kapellerfeld", "Kapfenberg", "Kapfenberg Fachhochschule",
			"Kappel am Krappfeld", "Karling", "Kasten", "Kastenreith",
			"Kathal", "Katsdorf", "Katzelsdorf", "Kefermarkt",
			"Kematen a. d. Krems", "Kematen in Tirol", "Kienberg-Gaming",
			"Kilb", "Kimpling", "Kindberg", "Kirchbach im Gailtal",
			"Kirchberg a. d. Pielach", "Kirchberg am Wagram",
			"Kirchberg in Tirol", "Kirchbichl", "Kirchdorf a. d. Krems",
			"Kirchstetten", "Kittsee", "Kittsee Gr.", "Kitzbühel",
			"Kitzbühel Hahnenkamm", "Klagenfurt Annabichl",
			"Klagenfurt Ebenthal", "Klagenfurt Hauptbahnhof",
			"Klagenfurt Lend", "Klagenfurt Ostbahnhof", "Klamm-Schottwien",
			"Klangen", "Klaus", "Klaus in Vorarlberg", "Kleblach-Lind",
			"Kledering", "Klein Harras", "Klein Meiseldorf-Maria Dreieichen",
			"Klein Pöchlarn", "Klein Wien", "Kleinhollenstein",
			"Kleinreifling", "Kleinzell", "Klosterneuburg-Kierling",
			"Klosterneuburg-Weidling", "Knittelfeld", "Kogelsbach", "Kolbnitz",
			"Korneuburg", "Kothmühle", "Kottingbrunn", "Kottingneusiedl",
			"Kottschallings", "Kranebitten", "Kraubath", "Kreilhof",
			"Kreisbach", "Krems a. d. Donau", "Kremsmünster",
			"Krenstetten-Biberbach", "Krieglach", "Kritzendorf",
			"Kroisbach-Zöbing", "Krummnußbaum", "Krumpendorf", "Kröllendorf",
			"Kuchl", "Kuchl Garnei", "Kufstein", "Kumpfmühl", "Kundl",
			"Königsberg", "Königsbrunn-Unterstockstall", "Kötschach-Mauthen",
			"Küb", "Küpfern", "Laa a. d. Thaya", "Laa a. d. Thaya Stadt",
			"Lacken", "Ladendorf", "Ladinach", "Lahnstein", "Lahrndorf",
			"Lahöfen", "Lambach", "Lambach Markt", "Landeck", "Landl",
			"Langen am Arlberg", "Langenlebarn", "Langenlois", "Langenwang",
			"Langenzersdorf", "Langkampfen", "Langwies",
			"Lanzendorf-Rannersdorf", "Lanzenkirchen", "Lasberg-St. Oswald",
			"Laubenbachmühle", "Lauffen", "Launsdorf-Hochosterwitz",
			"Lauterach", "Laxenburg-Biedermannsdorf", "Laßnitzhöhe",
			"Laßnitzthal", "Lebring", "Ledenitzen", "Lehen-Altensam",
			"Lehen-Ebersdorf", "Leibnitz", "Leithen", "Lend", "Lendorf",
			"Lengau", "Lenzing", "Lenzing Ort", "Leoben Hauptbahnhof",
			"Leobendorf-Burg Kreuzenstein", "Leobersdorf", "Leogang",
			"Leogang-Steinberge", "Leonding", "Leumühle", "Lichendorf",
			"Liebenfels", "Lienz", "Liezen", "Lilienfeld",
			"Lilienfeld Krankenhaus", "Limberg-Maissau", "Lind-Rosegg",
			"Lindau Hauptbahnhof", "Linz Ebelsberg", "Linz Franckstraße",
			"Linz Hauptbahnhof", "Linz Kleinmünchen", "Linz Oed",
			"Linz Urfahr", "Linz Wegscheid", "Linz-Pichling",
			"Lochau-Hörbranz", "Loich", "Loifarn", "Loipersbach Schattendorf",
			"Loosdorf", "Losenstein", "Ludesch", "Lungitz", "Lunz am See",
			"Lustenau", "Lustenau Markt", "Lödersdorf", "Mainburg",
			"Maishofen-Saalbach", "Mallnitz-Obervellach", "Mandling", "Mank",
			"Mannswörth", "Marbach-Maria Taferl", "Marchegg", "Marchtrenk",
			"Marein-St. Lorenzen", "Maria Anzbach", "Maria Elend im Rosenthal",
			"Maria Ellend a. d. Donau", "Maria Lanzendorf", "Maria Rain",
			"Maria Saal", "Mariahof-St. Lambrecht", "Mariazell",
			"Markersdorf a. d. Pielach", "Markt Paternion",
			"Markt Sachsenburg", "Markt St. Aegyd am Neuwalde", "Marktl",
			"Marz-Rohrbach", "Matrei", "Mattersburg", "Mattersburg Nord",
			"Mattighofen", "Matzen", "Mauer-Öhling", "Mauerkirchen",
			"Mautbrücken", "Mautern", "Mauthausen", "Meidling im Tal", "Melk",
			"Micheldorf", "Micheldorf-Hirt", "Michelhausen",
			"Miesenbach-Waidmannsfeld", "Mining", "Mirenau", "Mistelbach",
			"Mitterbach", "Mitterberghütten", "Mitterdorf-Veitsch",
			"Mitterndorf-Moosbrunn", "Mitterweißenbach",
			"Mittewald a. d. Drau", "Mittlern", "Mixnitz-Bärenschützklamm",
			"Mogersdorf", "Moosbierbaum-Heiligeneich", "Muckendorf-Wipfing",
			"Munderfing", "Munderfing Dampfsäge", "Mureck", "Mödling",
			"Möllbrücke-Sachsenburg", "Möllersdorf Aspangbahn", "Mötz",
			"Mühldorf im Lavanttal", "Mühldorf-Möllbrücke", "Mühlheim",
			"Mühling", "Mühling-Plaika", "Münchendorf", "Münster-Wiesing",
			"Mürzzuschlag", "Neckenmarkt-Horitschon", "Nendeln", "Nenzing",
			"Nettingsdorf", "Neubau-Kreuzstetten", "Neubruck", "Neudorf",
			"Neudörfl", "Neufelden", "Neuhaus a. d. Gail",
			"Neuhaus-Niederwaldkirchen", "Neuhofen a. d. Krems",
			"Neukirchen bei Lambach", "Neukirchen-Gampern", "Neulengbach",
			"Neulengbach Stadt", "Neumarkt a. d. Ybbs-Karlsbach",
			"Neumarkt in Steiermark", "Neumarkt-Kallham",
			"Neumarkt-Köstendorf", "Neunkirchen NÖ", "Neuratting",
			"Neusiedl am See", "Neustift", "Nickelsdorf", "Niederkreuzstetten",
			"Niedernfritz-St. Martin", "Niederöblarn", "Niklasdorf",
			"Nikolsdorf", "Nußbach", "Nöstlbach-St. Marien", "Nötsch",
			"Nüziders", "Obdach", "Ober Grafendorf", "Ober Olberndorf",
			"Ober Piesting", "Ober Radlberg", "Ober Waltersdorf", "Oberalm",
			"Oberbrunn", "Oberdrauburg", "Obereggendorf", "Obereinöd",
			"Oberfalkenstein", "Oberhart", "Oberhofen im Inntal",
			"Oberhofen-Zell am Moos", "Oberland", "Obernberg-Altheim",
			"Obersdorf", "Obersdorf-Pillichsdorf", "Obersee",
			"Oberthalheim-Timelkam", "Obertrattnach-Markt Hofkirchen",
			"Obertraun-Dachsteinhöhlen", "Obertraun-Koppenbrüllerhöhle",
			"Oberwart", "Oberweiden", "Oed", "Oepping", "Oftering",
			"Ollersbach", "Opponitz", "Ortmann", "Ossiach-Bodensdorf",
			"Ottensheim", "Ottnang-Wolfsegg", "Paasdorf", "Pama", "Parndorf",
			"Parndorf Ort", "Pasching", "Passau Hauptbahnhof", "Passering",
			"Paternion-Feistritz", "Patsch", "Paudorf", "Payerbach-Reichenau",
			"Peggau-Deutschfeistritz", "Penk", "Perchtoldsdorf", "Perg",
			"Perg Schulzentrum", "Pernegg", "Pernitz-Muggendorf",
			"Pernitz-Raimundviertl", "Pernitz-Wipfelhofstraße", "Persenbeug",
			"Petersbaumgarten", "Peterskirchen", "Petronell-Carnuntum",
			"Pettenbach", "Petzenkirchen", "Peutenburg", "Pfaffenschwendt",
			"Pfaffstätten", "Pfarrwerfen", "Pfenningbach", "Pichl", "Piesting",
			"Piesting Harzwerk", "Pill-Vomperbach", "Pillichsdorf",
			"Pinggau Freizeitzentrum", "Pinggau Markt", "Pinkafeld",
			"Pinkafeld Schule", "Pinsdorf", "Pirawarth", "Pitten", "Pixendorf",
			"Plank am Kamp", "Platt", "Postran", "Pottenbrunn",
			"Pottendorf-Landegg", "Pottenstein a. d. Triesting", "Pottschach",
			"Pram-Haag", "Preblau-Sauerbrunn", "Pregarten", "Pressegger See",
			"Preßbaum", "Priel", "Prinzersdorf", "Pritschitz", "Prottes",
			"Pruggern", "Puch", "Puch Urstein", "Puch bei Hallein",
			"Puchberg am Schneeberg", "Puchenau", "Puchenau West",
			"Puchenstuben", "Pulgarn", "Puntigam", "Pupping",
			"Purbach am Neusiedlersee", "Purgstall", "Purkersdorf Sanatorium",
			"Purkersdorf-Gablitz", "Purkla", "Pusarnitz", "Pöchlarn", "Pöckau",
			"Pöham", "Pöndorf", "Pörtschach am Wörthersee", "Pürbach-Schrems",
			"Pürgg", "Pürnstein", "Raaba", "Raasdorf", "Rabensburg",
			"Rabenstein NÖ", "Radstadt", "Raggendorf", "Raggendorf Markt",
			"Rainfeld-Klein Zell", "Ramingdorf-Haidershofen", "Rankweil",
			"Rattenberg-Kramsach", "Rattendorf-Jenig", "Ravelsbach",
			"Redl-Zipf", "Regelsbrunn", "Reichenfels-St. Peter", "Reichraming",
			"Reisach", "Reisenberg-Marienthal", "Reith", "Rekawinkel", "Retz",
			"Ried im Innkreis", "Riedau", "Riedenburg", "Riedlingsdorf",
			"Rietz", "Rohr Haltestelle", "Rohr-Bad Hall",
			"Rohrbach a. d. Gölsen", "Rohrbach-Berg", "Rohrbach-Vorau",
			"Rohrendorf", "Roppen", "Rosenau", "Rosenbach", "Rosenburg",
			"Rotheau-Eschenau", "Rothengrub", "Rothenthurn", "Rottenegg",
			"Roßleithen", "Rum", "Saalfelden", "Saffen", "Saimannslehen",
			"Salzburg Aigen", "Salzburg Gnigl", "Salzburg Hauptbahnhof",
			"Salzburg Kasern", "Salzburg Parsch", "Salzburg Sam",
			"Salzburg Süd", "Salzburg Taxham Europark", "San Candido/Innichen",
			"Sand", "Sarasdorf", "Sarmingstein", "Sattendorf", "Sattledt",
			"Sautern-Schiltern", "Saxen", "Schaan-Vaduz", "Schaanwald",
			"Schaftenau", "Scharnitz", "Scharnstein-Mühldorf", "Schauboden",
			"Schauersberg", "Scheibbs", "Scheiblingkirchen-Warth",
			"Scheifling", "Schiflugschanze Kulm", "Schildberg", "Schladming",
			"Schleinbach", "Schlierbach", "Schlins", "Schloß Haus", "Schlägl",
			"Schlöglmühl", "Schlüßlberg", "Schrambach", "Schwadorf",
			"Schwallenbach", "Schwanenstadt", "Schwarzach in Vorarlberg",
			"Schwarzach-St. Veit", "Schwarzenau",
			"Schwarzenbach a. d. Pielach", "Schwarzsee", "Schwaz", "Schwechat",
			"Schwerbach", "Schwertberg", "Schärding", "Schönau a. d. Enns",
			"Schönberg am Kamp", "Schönborn-Mallebern", "Schönfeld-Lassee",
			"Schönwies", "Schütt", "Schützen Haltestelle",
			"Schützen am Gebirge", "Sebersdorf", "Seebach bei Villach",
			"Seebenstein", "Seeburg", "Seefeld in Tirol",
			"Seekirchen am Wallersee", "Selker", "Selzthal", "Semmering",
			"Seyring", "Siebenbrunn-Leopoldsdorf", "Siebenhirten",
			"Siebenmühlen-Rosenau", "Sierndorf", "Sierndorf a. d. March",
			"Sigmundsherberg", "Silberwald", "Sillian", "Silz", "Simbach",
			"Sinnersdorf", "Sitzenberg Reidling", "Sollenau", "Sonntagberg",
			"Sopron", "Spielberg", "Spielfeld Straß", "Spillern",
			"Spital am Pyhrn", "Spital am Semmering", "Spittal-Millstättersee",
			"Spitz a. d. Donau", "Spratzern", "Spratzern Haltestelle",
			"St. Aegyd Eisenwerk", "St. Aegyd am Neuwalde",
			"St. Andrä im Lavanttal", "St. Andrä-Wördern",
			"St. Anton am Arlberg", "St. Daniel", "St. Egyden",
			"St. Georgen a. d. Gusen", "St. Georgen a. d. Gusen Hst",
			"St. Georgen a. d. Mattig", "St. Georgen am Längsee",
			"St. Georgen am Reith", "St. Georgen am Steinfeld",
			"St. Georgen ob Judenburg", "St. Jodok", "St. Johann im Pongau",
			"St. Johann im Rosental", "St. Johann in Tirol",
			"St. Johann in der Haide", "St. Johann-Weistrach",
			"St. Margarethen-Rammersdorf", "St. Margrethen",
			"St. Martin bei Traun", "St. Martin im Innkreis",
			"St. Martin-Sittich", "St. Michael", "St. Michael ob Bleiburg",
			"St. Nikola-Struden", "St. Pantaleon", "St. Paul", "St. Paul Bad",
			"St. Peter-Seitenstetten", "St. Pölten - Porschestraße",
			"St. Pölten - Traisenpark", "St. Pölten Alpenbahnhof",
			"St. Pölten Hauptbahnhof", "St. Ruprecht bei Villach",
			"St. Stefan im Lavanttal", "St. Stefan-Vorderberg",
			"St. Urban am Ossiachersee", "St. Valentin", "St. Veit a. d. Glan",
			"St. Veit a. d. Glan Westbahnhof", "St. Veit a. d. Gölsen",
			"St. Veit a. d. Triesting", "Staatz", "Stadt Haag",
			"Stadt Rottenmann", "Stadt Waidhofen a. d. Ybbs",
			"Stainach-Irdning", "Stallegg", "Stams", "Stans bei Schwaz",
			"Statzendorf", "Steeg-Gosau", "Stein a. d. Enns", "Stein-Mautern",
			"Steinach in Tirol", "Steinbachbrücke",
			"Steindorf am Ossiachersee", "Steindorf bei Straßwalchen",
			"Steinfeld im Drautal", "Steinhaus", "Steinhaus bei Wels",
			"Steinklamm", "Steinkogl", "Steinmühl", "Steinschal-Tradigist",
			"Steyr", "Steyr-Münichholz", "Steyregg", "Steyrling", "Stiefern",
			"Stiegengraben-Ybbstalerhütte", "Stillfried", "Stockerau",
			"Straning", "Strasshof", "Straßwalchen", "Studenzen-Fladnitz",
			"Stübing", "Suben", "Suetschach", "Sulz Museumsdorf",
			"Sulz-Röthis", "Summerau", "Szentgotthard", "Säusenstein",
			"Söchau", "Sölling", "Tainach-Stein", "Takern-St. Margarethen",
			"Tallesbrunn", "Tarvisio Boscoverde", "Tassenbach", "Tattendorf",
			"Tauchen-Schaueregg", "Tauchendorf-Haidensee",
			"Taufkirchen a. d. Pram", "Tauplitz", "Taxenbach-Rauris",
			"Taxwirt", "Teesdorf", "Teichstätt", "Telfs-Pfaffenhofen",
			"Tenneck", "Terfens-Weer", "Ternberg", "Ternitz", "Teufelsdorf",
			"Thal", "Thalheim-Pöls", "Theresienfeld", "Thörl-Maglern",
			"Tiffen", "Timelkam", "Tisis", "Traisen", "Traisen Markt",
			"Traiskirchen Aspangbahn", "Traismauer", "Trasdorf", "Trattenbach",
			"Traun", "Traunkirchen", "Traunkirchen Ort",
			"Trautmannsdorf a. d. Leitha", "Traxenbichl", "Treibach-Althofen",
			"Trieben", "Trumau", "Tröpolach", "Tulln", "Tulln Stadt",
			"Tullnerbach-Pressbaum", "Twimberg", "Töschling",
			"Ulmerfeld-Hausmening", "Ulrichskirchen", "Unter Buchberg",
			"Unter Höflein", "Unter Kritzendorf", "Unter Oberndorf",
			"Unter Purkersdorf", "Unter Radlberg", "Unter Tullnerbach",
			"Unter Waltersdorf", "Unterberg-Stefansbrücke", "Untereggendorf",
			"Unterhart", "Unterloiben", "Unterpetersdorf", "Unterretzbach",
			"Untersiebenbrunn", "Unzmarkt", "Urschendorf", "Uttendorf-Helpfau",
			"Velden am Wörthersee", "Vellach-Khünburg", "Viechtwang",
			"Viehofen", "Viktring", "Villach Hauptbahnhof",
			"Villach Westbahnhof", "Vitis", "Vogelsang", "Voitsdorf",
			"Volders-Baumkirchen", "Vöcklabruck", "Vöcklamarkt",
			"Völkermarkt-Kühnsdorf", "Völs", "Wagram-Grafenegg", "Waidegg",
			"Waidhofen a. d. Thaya", "Waidhofen a. d. Ybbs",
			"Waidhofen a. d. Ybbs Lokalbahn",
			"Waidhofen a. d. Ybbs-Schillerpark", "Wald am Schoberpaß",
			"Waldegg", "Waldegg-Dürnbach", "Walding", "Wallersee",
			"Wampersdorf", "Wankham", "Warmbad Villach",
			"Wartberg a. d. Krems", "Wartberg im Mürztal", "Watschig",
			"Weigelsdorf", "Weikendorf", "Weikendorf-Dörfles", "Weinburg",
			"Weins-Isperdorf", "Weissenbach-Neuhaus", "Weissenbach-St. Gallen",
			"Weissenkirchen in der Wachau", "Weissenstein-Kellerberg",
			"Weitenegg", "Weitersfeld a. d. Mur", "Weitlanbrunn",
			"Weizelsdorf", "Weizelsdorf Ort", "Weißkirchen",
			"Wels Hauptbahnhof", "Wels Lokalbahn", "Wendling", "Weng",
			"Werfen", "Werndorf", "Wernstein", "Westendorf", "Weyer",
			"Wien Atzgersdorf", "Wien Blumental", "Wien Breitenleer Straße",
			"Wien Breitensee", "Wien Brünner Straße",
			"Wien Erzherzog Karl-Straße", "Wien Floridsdorf",
			"Wien Franz-Josefs-Bahnhof", "Wien Geiselbergstrasse",
			"Wien Gersthof", "Wien Grillgasse", "Wien Hadersdorf",
			"Wien Haidestraße", "Wien Handelskai", "Wien Hausfeldstrasse",
			"Wien Heiligenstadt", "Wien Hernals", "Wien Hetzendorf",
			"Wien Hirschstetten", "Wien Hütteldorf", "Wien Inzersdorf",
			"Wien Jedlersdorf", "Wien Kaiserebersdorf",
			"Wien Krottenbachstraße", "Wien Leopoldau", "Wien Lobau",
			"Wien Matzleinsdorfer Platz", "Wien Meidling", "Wien Mitte",
			"Wien Nußdorf", "Wien Oberdöbling", "Wien Ottakring",
			"Wien Penzing", "Wien Praterkai", "Wien Praterstern",
			"Wien Rennweg", "Wien Siemensstraße", "Wien Simmering",
			"Wien Speising", "Wien Spittelau", "Wien St. Marx", "Wien Stadlau",
			"Wien Strebersdorf", "Wien Südbahnhof", "Wien Südtiroler Platz",
			"Wien Süßenbrunn", "Wien Traisengasse", "Wien Weidlingau",
			"Wien Westbahnhof", "Wien Wolf in der Au", "Wien Zentralfriedhof",
			"Wien-Liesing", "Wiener Neustadt Anemonensee",
			"Wiener Neustadt Civitas Nova", "Wiener Neustadt Hbf",
			"Wiener Neustadt Nord", "Wienerbruck-Josefsberg",
			"Wieselburg a. d. Erlauf", "Wiesen-Sigleß", "Wiesenau",
			"Wiesenfeld-Schwarzenbach", "Wiesenschwang-Oberndorf", "Wiesmühle",
			"Wildon", "Wildungsmauer", "Wilfleinsdorf", "Wilfling",
			"Wilhelmsburg a. d. Traisen", "Willendorf",
			"Willendorf in der Wachau", "Windau", "Winden", "Windigsteig",
			"Windischgarsten", "Winkl im Rosental", "Winterbach", "Winzendorf",
			"Wittmannsdorf", "Wolfsberg", "Wolfsbergkogel", "Wolfshütte",
			"Wolfsthal", "Wolfurt", "Wolkersdorf", "Wopfing",
			"Wulkaprodersdorf", "Wulkaprodersdorf Haltestelle", "Wöllersdorf",
			"Wörgl Hauptbahnhof", "Wörgl Süd-Bruckhäusl",
			"Wörschach Schwefelbad", "Wösendorf-Joching", "Ybbs a. d. Donau",
			"Ybbsitz", "Zeiselmauer-Königstetten", "Zell a. d. Pram",
			"Zell am See", "Zellerndorf", "Zeltweg", "Ziersdorf", "Zirl",
			"Zurndorf", "Zwettl", "Zwettl Stadt", "Zöbing", "Öblarn", "Ötztal",
			"Übersbach" };
}
